### ISSUE TITLE
FATAL:nss_util.cc(156)] nss_error=-5925, os_error=0

### ISSUE THREAD

**Issue by probonopd** [probonopd/nativefier-appimage#1]
Does not run on `xubuntu-18.04-desktop-amd64.iso`:

```
Downloads/NoteCAD-1cbe7ae-x86_64.AppImage: /tmp/.mount_NoteCAnDXIM7/usr/bin/../lib/libdbus-1.so.3: no version information available (required by Downloads/NoteCAD-1cbe7ae-x86_64.AppImage)
/tmp/.mount_NoteCAnDXIM7/usr/bin/note-cad: /tmp/.mount_NoteCAnDXIM7/usr/bin/../lib/libdbus-1.so.3: no version information available (required by /tmp/.mount_NoteCAnDXIM7/usr/bin/note-cad)
[4418:0105/133327.616142:FATAL:nss_util.cc(156)] nss_error=-5925, os_error=0
Aborted

me@host:~$ sudo apt-get install libnss3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libnss3 is already the newest version (2:3.35-2ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 435 not upgraded.
```

**Comment by probonopd** [comment]
Possibly related to https://github.com/probonopd/linuxdeployqt/issues/35

**Comment by probonopd** [comment]
```
me@host:~$ LD_DEBUG=libs Downloads/NoteCAD-1cbe7ae-x86_64.AppImage
(...)
      4998:	  trying file=/usr/lib/libsoftokn3.so
      4998:	
      4998:	/tmp/.mount_NoteCADSheYd/usr/bin/note-cad: error: symbol lookup error: undefined symbol: localtime64 (fatal)
      4998:	/tmp/.mount_NoteCADSheYd/usr/bin/note-cad: error: symbol lookup error: undefined symbol: localtime64_r (fatal)
[4998:0105/133835.092086:FATAL:nss_util.cc(156)] nss_error=-5925, os_error=0

me@host:~$ grep -r libsoftokn3 squashfs-root/
Binary file squashfs-root/usr/lib/libnss3.so matches
```

**Comment by probonopd** [comment]
```
me@host:~$ rm ssquashfs-root/usr/lib/libnss*
```

Runs. But it may have undesired side effects for some distributions.

**Comment by probonopd** [comment]
Only shows a white page though; not sure yet why.

When using http rather than https, then it loads.

**Comment by probonopd** [comment]
https://public-cdn.cloud.unity3d.com/hub/prod/UnityHubSetup.AppImage works; what have they done differently?

They are not shipping the problematic libs:

```
me@host:~$ find /tmp/.mount_UnityHdCJ1L6/ | grep nss
me@host:~$ find /tmp/.mount_UnityHdCJ1L6/ | grep soft
```

Reference:
https://github.com/AppImage/appimage.github.io/pull/928

**Comment by liyuzhao** [comment]
I met the same problem, how did you solve it? @probonopd

**Comment by probonopd** [comment]
Maybe @azubieta's https://github.com/AppImageCrafters/appimage-builder can solve this.

**Comment by azubieta** [comment]
Regarding the issue, provably some required lib is not being bundled (maybe a plug-in), `strace -ff -e trace=file <your binary>` may help you find what's being loaded from the system. Once you find it just add it to the bundle.

appimage-builder does embed that lib and many others, it relies on the knowledge contained the Debian/Ubuntu package system to resolve dependencies (reading the needed section of an ELF binary is not enough).

**Comment by probonopd** [comment]
@liyuzhao Which distribution are you using? Please retry using Ubuntu xenial. Does the problem also exist there?

**Comment by liyuzhao** [comment]
> @liyuzhao Which distribution are you using? Please retry using Ubuntu xenial. Does the problem also exist there?

Yes, I didn't solve it.I don't have a solution

**Comment by liyuzhao** [comment]
> Regarding the issue, provably some required lib is not being bundled (maybe a plug-in), `strace -ff -e trace=file <your binary>` may help you find what's being loaded from the system. Once you find it just add it to the bundle.
> 
> appimage-builder does embed that lib and many others, it relies on the knowledge contained the Debian/Ubuntu package system to resolve dependencies (reading the needed section of an ELF binary is not enough).

thanks so much ,I solve my problem with you remind(strace -ff -e trace=file <your binary> ).
You are very strong！！！
